title: VAMOS 2019
description: 13th International Workshop on Variability Modelling of Software-Intensive Systems
             February 6-8, 2019, Leuven Belgium

theme: jekyll-theme-cayman


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
